import 'dart:io'; // for input and output 

void clearScreen() { // clear screen 
  if (Platform.isWindows) {
    // For Windows (cls command)
    Process.runSync('cls', [], runInShell: true);
  } else {
    // For Linux, macOS, and other Unix-like systems
    Process.runSync('clear', [], runInShell: true);
  }
}

class Animal { // Animal Class Declaration
  String name; // strings
  String kingdom;
  String dob;
  int numlegs; // integers
  String walkDirection;

  Animal(this.name, this.kingdom, this.dob, this.numlegs, this.walkDirection); // constructor

  void walk(String direction) { // Method for walk (uses direction parameter)
    
    if (numlegs <= 0) { // conditionals (if else error handling)
      print('$name cannot walk because it has no legs');
    } else {
      print('$name is going towards $direction');
    }

  }

  void displayInfo() {// Method for displaying all info
    print('Name: $name');
    print('Kingdom: $kingdom');
    print('Date of Birth: $dob');
  }
}

class Pet {
  String? nickname; // using ? for allowing null variables (for constructor)
  int kindness = 0;

  // 2 Constructors
  Pet.withNickname(this.nickname) : kindness = 1000; // initalizer list
  Pet.withoutNickname(); 

  void kick(){ // kick method (to lessen kindness)
    print("You have kicked your pet! Kindness decreased");
    kindness -= 10; 
  }

  void pet(){ // pet method (to add kindness)
    if(kindness <= 0){ // 
      print("The pet hates you! It keeps running away when you try to pet!");
    } else {
      print("You gave care to your pet! Kindness Increased");
      kindness += 10;
    }
  }

  void feed(){ // feed method (to lessen or add kindness)
    stdout.write("Would you like to feed your pet (y/n)?: ");
    String? input = stdin.readLineSync()?.trim().toLowerCase(); 

      if(input == 'y') {
        kindness += 1200;
        print("You fed your pet! Kindness increased!");
      } else if (input == 'n'){
        kindness -= 1200;
        print("You didn't feed your pet! Kindness decreased!");
      } else {
        print("Invalid Option, Please Enter y or n only");
      }  
  }

  void displayInfo(){ // display info and kindness meter of a pet
    print("Nickname: $nickname");
    print("Kindness Meter: $kindness");
  }
}

void main() {// entry point
 
  List<Animal> ZOO = [ // list of Animals (Generated by Gemini)
  Animal("Leo", "Animalia", "12/05/2018", 4, "North"),
  Animal("Hooty", "Aves", "30/10/2021", 2, "East"),
  Animal("Bubbles", "Actinopterygii", "15/01/2023", 0, "South"),
  Animal("Slither", "Reptilia", "05/07/2019", 0, "West"),
  Animal("Manny", "Mammalia", "22/03/2015", 4, "North-West")
  ];

  List<Pet> PET_HOME = [ // list of Pets (Generated by Gemini)
  Pet.withNickname("Luna"),      
  Pet.withoutNickname()   
  ];

  void printZOO(List<Animal> animals) { // loop list an call each method
   
    for(var animal in animals){
      print("======== ANIMAL PROFILE =========="); // placeholders
      animal.displayInfo();
      animal.walk(animal.walkDirection);
      print("==================================\n");

    }
  }

  void printPet(List<Pet> pets){ // loop list and call each method

    for(var pet in pets){
      pet.kick(); // call all 3 methods in the pet class
      pet.pet();
      pet.feed();

      print("\n=========== PET PROFILE =========="); // placeholder
      pet.displayInfo();
      print("==================================\n");
    }
  }


  // calling methods
  clearScreen(); // clearscreen first
  printZOO(ZOO); // list all animals
  printPet(PET_HOME); // list all pets

}
