import 'animal.dart';
import 'pet.dart';
import 'dart:io'; // for input and output 

void clearScreen() { // clear screen 
  if (Platform.isWindows) {
    // For Windows (cls command)
    Process.runSync('cls', [], runInShell: true);
  } else {
    // For Linux, macOS, and other Unix-like systems
    Process.runSync('clear', [], runInShell: true);
  }
}



void main() {// main method
  List<Animal> ZOO = [ // list of Animals (Generated by Gemini)
  Animal("Leo", "Animalia", "12/05/2018", 4, "North"),
  Animal("Hooty", "Aves", "30/10/2021", 2, "East"),
  Animal("Bubbles", "Actinopterygii", "15/01/2023", 0, "South"),
  Animal("Slither", "Reptilia", "05/07/2019", 0, "West"),
  Animal("Manny", "Mammalia", "22/03/2015", 4, "North-West")
  ];

  List<Pet> PET_HOME = [ // list of Pets (Generated by Gemini)
  Pet.withNickname("Luna", "Mammal", "2022-01-01", 4, "North", "Lunatic"),      
  Pet.withoutNickname("Rex", "Mammal", "2021-05-12", 4, "West"),   
  ];

  void printZOO(List<Animal> animals) { // loop list an call each method
   
    for(var animal in animals){
      print("======== ANIMAL PROFILE =========="); // placeholders
      animal.displayInfo();
      animal.walk(animal.walkDirection);
      print("==================================\n");

    }
  }

  void printPet(List<Pet> pets){ // loop list and call each method

    for(var pet in pets){
      pet.kick(); // call all 3 methods in the pet class
      pet.pet();
      pet.feed();

      print("\n=========== PET PROFILE =========="); // placeholder
      pet.displayInfo();
      print("==================================\n");
    }
  }


  // calling methods
  clearScreen(); // clearscreen first
  printZOO(ZOO); // list all animals
  printPet(PET_HOME); // list all pets

}
